### ISSUE TITLE
Editorialization in usernames.md

### ISSUE THREAD

**Issue by tesk9** [delasky/slack_usernames#2]
This is a community art project, and so it is extremely important to allow community voices to shine through. Community voices say regex is sensible, and that no one has yet suggested sensible-dan as a username suggestion.

**Comment by jrogozen** [comment]
I think we shouldn't be too quick to approve 'half-baked' features such as this one. In large projects like this it's important to keep scalability in mind. In fact, I'm worried that the proposed changes are actually in direct opposition to this repo's core values : ).

**Comment by tesk9** [comment]
Is there a wiki where someone expounds upon the repo's core values? They are written nowhere.
Furthermore, even if the repo's values were encapsulated somewhere, it is vital to the development process to be able to pivot quickly. Being able to redefine core values is central to this.
Re: "half-baked."
![image](https://cloud.githubusercontent.com/assets/8811312/8316777/1525213c-19ae-11e5-89a7-825a97523219.png)

**Comment by delasky** [comment]
@tesk9 thank you for your contribution to this project! No one is denying the utility of adding a sample regex to usernames.md. If you update your pull request _with sensible tests_ I'm sure that it will be merged in! What is objectionable is your continual flouting of this projects core values. It makes me wonder whether you support open source development at all!!

**Comment by jrogozen** [comment]
Just to echo what @delasky has already said, we believe in the open source community, freedom, and creativity. For as long as this project has existed, we've maintained that we will not sacrifice our core values for instant 'progress,' or even worse, 'progress for the sake of progress'.

I agree that the repo could benefit from a slight documentation touch-up, but I certainly don't think we have to go so far as to bash @delasky for his failure to add largely trivial/fluff content to a project he already has generously devoted hundreds of hours to.

Those potatoes are actually fully baked, they're simply cut in half!

**Comment by tesk9** [comment]
These vicious attacks on half-baked potatoes have left me unsure of my willingness to contribute to this project going forward.
![image](https://cloud.githubusercontent.com/assets/8811312/8317075/ce72ad66-19af-11e5-9b50-5c07adbabbcf.png)

**Comment by jrogozen** [comment]
Nooo please stay, Dan and I are lonely :(.

**Comment by delasky** [comment]
In response to some of the previous comments in this thread. Am I a selfless martyr for maintaining this project? Of course. But even a person as gloriously exalted as a project maintainer is only as successful as the team around him/her. I believe that the intensity of this debate is just a reflection of the passion that we are all putting into this project. @tesk9, your pull request was a pile of a garbage, but your intentions were good, and even though slogging through aforementioned hot garbage has cost us thousands of man hours we could have been devoting to writing SICK CODE, we forgive you, and hope you will continue to contribute, BETTER tho please.

**Comment by tesk9** [comment]
### `<3`
